# Generated by Django 5.0.6 on 2024-09-09 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_video_rename_image_image_file_alter_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.video')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.ManyToManyField(through='board.PostVideo', to='board.video'),
        ),
    ]
