# Generated by Django 5.0.6 on 2024-09-09 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_comment_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Пост-Изображение'},
        ),
        migrations.AlterModelOptions(
            name='postvideo',
            options={'verbose_name': 'Пост-Видео'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(help_text='Первое фото будет выбрано в качестве превью', on_delete=django.db.models.deletion.CASCADE, to='board.post', verbose_name='Пост'),
        ),
    ]
