# Generated by Django 5.0.6 on 2024-09-18 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_onetimecode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimecode',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
